name: esbuild-bundle-analyzer
description: Analyzes each PR's impact on esbuild bundle size
inputs:
  name:
    required: false
    default: ${{ github.event.repository.name }}
    description: |
      The name of your project. This will be used in the comment header.
  metafiles:
    required: true
    description: |
      A comma-separated list of paths to [esbuild's meta file]([https://esbuild.github.io/api/#metafile]).
      Must be non-empty.
      Glob (`dist/**/meta.json`) is supported. 
      
      As of esbuild v0.20.0, you need to write the meta file by yourself after build, something like this:
      
      ```javascript
      import * as esbuild from 'esbuild'
      import fs from 'node:fs'
      
      let result = await esbuild.build({
        entryPoints: ['src/app1.js', 'src/app2.js'],
        bundle: true,
        metafile: true,
        outdir: 'dist',
      })
      
      fs.writeFileSync('dist/meta.json', JSON.stringify(result.metafile))
      ```
      
      In this case, the `metafiles` config should be `"dist/meta.json"`.
      
      Typically, you only need one meta file since one meta file can contain multiple out files information.
      Multiple meta files may be useful for more complex scenarios.
  analyze_directory:
    required: false
    default: ".analyzer"
    description: |
      A path to working directory where bundle analysis are stored.
  include_extensions:
    required: false
    default: ".js,.cjs,.mjs"
    description: |
      A comma-separated list of file extension to be included in the analysis table.
  percent_extra_attention:
    required: false
    default: "20"
    description: |
      If an out file size has increased more than this percent, display a "‼️" to draw attention
      to the change.
  show_details:
    required: false
    default: "true"
    description: |
      If `true`, a collapsed "details" section is rendered. It explains the details of the numbers provided and icons.
  show_no_change:
    required: false
    default: "true"
    description: |
      If `true`, all bundles are shown in the analysis regardless of size change. If `false`, only bundles with size changes are shown.
  top_n_largest_paths:
    required: false
    default: "20"
    description: |
      The number of largest paths (e.g.) `node_modules/foo`) to be collected.
      If 0 or lower, skipped.   

runs:
  using: composite
  steps:
    - name: Download base branch bundle stats
      uses: dawidd6/action-download-artifact@v6
      # Ok to continue on error since the base branch has no bundle analysis artifact for the first setup
      continue-on-error: true
      if: success() && github.event.number
      with:
        branch: ${{ github.event.pull_request.base.ref }}
        path: ${{ inputs.analyze_directory }}/base

    - name: Compare with base branch bundle
      shell: bash
      if: success()
      env:
        INPUT_METAFILES: ${{ inputs.metafiles }}
        INPUT_NAME: ${{ inputs.name }}
        INPUT_ANALYZE_DIRECTORY: ${{ inputs.analyze_directory }}
        INPUT_INCLUDE_EXTENSIONS: ${{ inputs.include_extensions }}
        INPUT_PERCENT_EXTRA_ATTENTION: ${{ inputs.percent_extra_attention }}
        INPUT_SHOW_DETAILS: ${{ inputs.show_details }}
        INPUT_SHOW_NO_CHANGE: ${{ inputs.show_no_change }}
        INPUT_TOP_N_LARGEST_PATHS: ${{ inputs.top_n_largest_paths }}
      run: |
        node ${{ github.action_path }}/dist/index.mjs

    - name: Upload bundle analysis on default branch
      uses: actions/upload-artifact@v4
      if: success() && github.ref_name == github.event.repository.default_branch
      with:
        name: bundle
        path: ${{ inputs.analyze_directory }}/bundle_analysis.json

    - name: Find Comment
      uses: peter-evans/find-comment@v3
      if: success() && github.event.number
      id: fc
      with:
        issue-number: ${{ github.event.number }}
        body-includes: '<!-- __ESBUILD_BUNDLE_${{ inputs.name }} -->'

    - name: Create Comment
      uses: peter-evans/create-or-update-comment@v4
      if: success() && github.event.number && steps.fc.outputs.comment-id == 0
      with:
        issue-number: ${{ github.event.number }}
        body-path: ${{ inputs.analyze_directory }}/bundle_analysis_comment.txt

    - name: Update Comment
      uses: peter-evans/create-or-update-comment@v4
      if: success() && github.event.number && steps.fc.outputs.comment-id != 0
      with:
        issue-number: ${{ github.event.number }}
        body-path: ${{ inputs.analyze_directory }}/bundle_analysis_comment.txt
        comment-id: ${{ steps.fc.outputs.comment-id }}
        edit-mode: replace
branding:
  icon: 'package'
  color: 'yellow'
